version: '3.8'
volumes:
  mongo-data: { }
  redis-data: { }
  typesense-data: { }

secrets:
  db_password:
    file: db_password.txt
  redis_password:
    file: redis_password.txt
  typesense_api_key:
    file: typesense_api_key.txt

services:
  jikan_rest: &jikan_rest
    image: jikanme/jikan-rest:latest
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    secrets:
      - db_password
      - typesense_api_key
    environment:
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@\h] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
      APP_DEBUG: 'false'
      APP_ENV: production
      CACHING: 'true'
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD__FILE: /run/secrets/redis_password
      DB_CONNECTION: mongodb
      DB_HOST: mongodb
      DB_DATABASE: jikan
      DB_PORT: 27017
      DB_ADMIN: "${DB_USERNAME:-root}"
      DB_USERNAME: "${DB_USERNAME:-root}"
      SCOUT_DRIVER: typesense
      SCOUT_QUEUE: 'false'
      DB_PASSWORD__FILE: /run/secrets/db_password
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: 8108
      TYPESENSE_API_KEY__FILE: /run/secrets/typesense_api_key
      CORS_MIDDLEWARE: 'true'
      MICROCACHING: 'true'
      MICROCACHING_EXPIRE: 60
    depends_on:
      mongodb: { condition: service_healthy }
      redis: { condition: service_healthy }
      typesense: { condition: service_healthy }

  web:
    <<: *jikan_rest
    ports:
      - '8080:8080/tcp'
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --spider -q "http://127.0.0.1:2114/health?plugin=http"' ]
      interval: 2s
      timeout: 2s

  mongodb:
    image: mongo:focal
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017/tcp'
    command: --wiredTigerCacheSizeGB ${MONGO_CACHE_SIZE_GB:1}
    secrets:
      - db_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://localhost:27017 --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    secrets:
      - redis_password
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:-null}"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${cat /run/secrets/redis_password}"
    volumes:
      - redis-data:/data:rw
    ports:
      - '6379/tcp'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 500ms
      timeout: 1s

  typesense:
    image: typesense/typesense:0.24.1
    entrypoint: /bin/sh
    secrets:
      - typesense_api_key
    command:
      - -c
      - TYPESENSE_API_KEY="$$(cat /run/secrets/typesense_api_key)" /opt/typesense-server --data-dir /data
    restart: no
    volumes:
      - typesense-data:/data
    ports:
      - "8108/tcp"
